defaults:
    - _self_
    - datamodule: default
    - model: default
    - trainer: default
    - experiment: default

seed: 46762398
ckpt_path: null
train: true
test: false

path:
    exp_root: exp
    figures: figures
    
version_base: null
hydra:
    run:
        dir: ${path.exp_root}/${hydra.runtime.choices.experiment}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${hydra.job.override_dirname}
    job:
        config:
            override_dirname:
                kv_sep: '-'
                item_sep: '_'
                exclude_keys: 
                    - path.exp_root
                    - experiment
                    - ckpt_path
